// Code generated by MockGen. DO NOT EDIT.
// Source: ./limiter/limiter.go
//
// Generated by this command:
//
//	mockgen.exe -source=./limiter/limiter.go -package=limitermock -destination=./limiter/mocks/limiter.mock.go
//
// Package limitermock is a generated GoMock package.
package limitermock
