
services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root






