
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root






